language: node_js

stages:
  - deps
  - build
  - test

jobs:
  include:
    - stage: deps
      script:
       - cd openvidu-browser
       - npm i
    - stage: build
      script:
        - cd openvidu-browser
        - npm i
        - npm run build

