language: node_js
node_js:
  - "node"

stages:
  - deps
  - build
  - test

jobs:
  include:
    - stage: deps
      script:
       - cd openvidu-browser
       - yarn install
    - stage: build
      script:
        - cd openvidu-browser
        - yarn install
        - yarn build

